### ISSUE TITLE
Incorrect I/O when reading grayscale jpeg image

### ISSUE THREAD

**Issue by Mokosha** [nothings/stb#92] opened 2015-03-24 20:47 UTC
I ran the following program on a Windows 7 machine under Visual Studio 2013. To my knowledge, SSE2 is available.

    #include <tchar.h>
    #include <cassert>

    #define STB_IMAGE_IMPLEMENTATION
    #include "stb_image.h"

    #define STB_IMAGE_WRITE_IMPLEMENTATION
    #include "stb_image_write.h"

    int _tmain(int argc, _TCHAR* argv[])
    {
    	int width, height, nChannels;
    	unsigned char *pixelData = stbi_load("test.jpg", &width, &height, &nChannels, 0);
    	assert(nChannels == 1);

    	if (!stbi_write_png("test-out.png", width, height, nChannels, pixelData, width*nChannels)) {
    		return 1;
    	}

    	return 0;
    }

Here are the source and result images:

### `test.jpg`
![test](https://cloud.githubusercontent.com/assets/885364/6812412/f40edc1e-d22b-11e4-93c8-e06d9a6b6c47.jpg)

### `test-out.png`
![test-out](https://cloud.githubusercontent.com/assets/885364/6812421/03887db2-d22c-11e4-9c74-e8cd3fdd33d3.png)

Not sure why, but the rows of pixels at the bottom of the image are not right.

**Comment by Mokosha** [comment] 2015-03-25 07:19
FWIW, the same happens on a MacBook Pro running Yosemite 10.10 under clang 3.5

**Comment by nothings** [comment] 2015-04-12 18:29
Note to self: it appears that the file terminates in the middle of the last progressive refinement, and we read all 0s and this huffman decodes to '0x01' which causes us to set every pre-quantized AC to 1, and the blocks are what you get from dcting those after dequantization. (This seems a little implausible, but that's the best I can tell.)

jpgd stuffs the empty bit-buffer with an EOS marker, but appears to not be *looking*  for those in its huffman buffer filler so that doesn't make any sense. ijg libjpeg comments claim they just stuff with 0s at end of file. Need to find a jpeg lib that is public domain and that works for this file and log what huffman values it decodes.

**Comment by rygorous** [comment] 2015-04-19 07:44
I looked into this today. The IJG code seems to have an "optimization" to short-circuit when there are no more bits left to be read. The problem is that the behavior in that case is not actually the same as the spec-mandated behavior when reading an infinite string of zero bytes.

Short version, the IJG code has an if around the whole AC scan reading that is equivalent to adding a "if (j->nomore) return 1;" at the start of jpeg_decode_block_prog_ac (I added this after the spec_start check). That fixes most of it. I still get the 3 dimmer garbage blocks from just before the "dot dot dot" pattern that continues until the end of the image. Not sure where they come from.

It looks like this JPEG file was obtained by an aggressive JPEG optimizer that assumes bug-for-bug compatibility with the IJG code. It's certainly *not* a well-formed bit stream - the IJG code will actually warn about data corruption when decoding this file. The same code that sets the "insufficient data" flag, which is the IJG equivalent of "j->nomore", dispatches a warning callback.

**Comment by nothings** [comment] 2015-04-19 08:31
Sigh.

**Comment by rygorous** [comment] 2015-04-19 08:49
Don't worry, ignore that. I spent some more time on this and it turns out it's actually a much simpler issue - progressive AC decoding logic is just wrong (found when trying to track down why the block edges with stb_image seemed much more "frazzled" than what I see in the browser).

PR with fix incoming.

**Comment by nothings** [comment] 2015-04-19 11:20
Fixed in version 2.05.

**Closed by nothings** 2015-04-19 11:20 UTC
Labels: bug, stb_image

**Comment by Mokosha** [comment] 2015-04-19 17:59
Thanks!
