### ISSUE TITLE
STB_Image - decoding image into preallocated memory

### ISSUE THREAD

**Issue by Kerndog73** [nothings/stb#372] opened 2016-11-29 03:18 UTC
Is there a way to use the library to decode an image into some memory already allocated by the user. the STBI_ALLOC macro does help in this situation because I would have to store the allocation size of the image in global state and have the macro call a function that checks the allocation size against the image size so we know its the image thats being allocated. Then hand in the memory we've allocated.

I was thinking there might be a way to produce a stbi__context with pointer in it to trick the library into thinking that its already allocated the memory when in fact it is the user that did it. But I couldn't figure which member to put the pointer in.

Is there a function that does this or some trick somewhere?

Thanks

**Comment by nothings** [comment] 2016-11-29 10:55
Duplicate of https://github.com/nothings/stb/issues/58

But really you should just let stb_image create the image in its buffer and then copy it to your pre-allocated buffer. Depending on the file format, stb_image already copies around multiple image-sized buffers, so one final copy on your side shouldn't make that much of a performance difference.

**Closed by nothings** 2016-11-29 10:55 UTC
