### ISSUE TITLE
JPEG writing completly broken since recent commit [stb_image_write.h]

### ISSUE THREAD

**Issue by SairesArt** [nothings/stb#718] opened 2019-02-23 11:34 UTC
Hey there.
I was surprised to find stbi_write_jpg() writing garbage images or SegFaulting, when I cloned this repo.
I went back the commit history and found the culprit.
Every other write function works flawlessly.

- Merge branch 'stbiw-fix-jpeg-flipping' of https://github.com/DanielGibbson/stb into working  ( b2bde485a2b1367450a5fe007038de6073cb75c3 )

Last working commit

- stb_image; optimize row computation in PR ( e5d4d6fcce00ba8c4ec2ca0dec4c0d0b804d89fb )

This commit fails to compile with error
 ```
stb_image_write.h:1473:19: error: ‘p’ undeclared (first use in this function)
p = (stbi__flip_vertically_on_write ? (height-1-row) : row)*width*comp;
```

- stb_image_write: fix the previous fix (incorrectly labelled as stb_image ( 476c1f89a237871571471edbf38d7b6fbb590b33 ) 

Every commit younger including this one produces garbage jpegs or segfaults.

**Comment by rygorous** [comment] 2019-02-23 11:37
Duplicate of #706.

**Closed by rygorous** 2019-02-23 11:37 UTC
