### ISSUE TITLE
stb_image: Output pixels to existing memory

### ISSUE THREAD

**Issue by Peach1** [nothings/stb#855] opened 2019-12-13 17:41 UTC
Is is possible to output image pixels to existing memory?
Right now if you have an external buffer, you end up allocating twice and you have to copy the output pixel data instead of just allocating an array once and having stbi_load write into it

One use case is loading pixels directly into a C++ vector;
Or loading small images directly into the stack memory.

```c
unsigned char pixels[128*128*4];
out = stbi_load(filename, &w, &h, &bpp, 0);
memcpy(pixels, out, w*h*bpp);
free(out);
```

```c
unsigned char pixels[128*128*4];
stbi_info(filename, w, h, bpp);
stbi_load_into(pixels); // writes directly without allocating
```

Is there a way to do this currently or would this be a new feature?

**Comment by nothings** [comment] 2019-12-13 17:50
There's no way to do this currently.

Duplicate of #58.

**Closed by nothings** 2019-12-13 17:50 UTC
