### ISSUE TITLE
fopen failing to load png on windows

### ISSUE THREAD

**Issue by Lecale** [nothings/stb#833] opened 2019-11-13 11:58 UTC
Unfortunately I am coming to from this project from Nim
https://gitlab.com/define-private-public/stb_image-Nim/issues/8
The background to the issue is here.
Can you suggest for me where I should go about adding additional printf statements into the header file in order to help debug the issue? Sadly I am not a C user, I don't count being able to do the basics beginner exercises. However, I would love to be able to use this library.
I've reproduced my problem on 2 different windows machines, with more than 1 compiler.
Apologies for raising an issue from an indirect route!

**Comment by nothings** [comment] 2019-11-13 13:18
There's nothing for me to do, it just means it can't find a file of the name you've specified at the location you've specified. You are probably misspelling the filename or it is not in the current directory or whatever path you are specifying. There are many ways this could happen, and there is no way for stb_image to know.

**Comment by Lecale** [comment] 2019-11-13 13:34
Incorrect path was the first suggestion I had when I first raised this bug. I did try relative and absolute, and am pretty sure that I remember confirming that other stb_image functions could access the file.

**Comment by nothings** [comment] 2019-11-13 13:58
Oh god, I take it back, I forgot it had all that crazy UTF-8 support in it. Let me look.

**Comment by nothings** [comment] 2019-11-13 14:19
Ok, it looks like the Nim wrapper doesn't define STB_WINDOWS_UTF8, the original thing should be true. It just calls fopen_s() with the filename you passed in.

I will return to my claim that this is on the Nim wrapper developer to figure out. It's clear in from the referenced issue that he can't reproduce it--AND HE'S USING NIM. I'm not going to be able to reproduce it either and I'm further from the problem than you. And because it's failing in a single C library call, there's still nothing useful you can do in the header file, other than printing out errno, which is of such minimal utility I literally never use it.

**Comment by Lecale** [comment] 2019-11-13 14:22
Thank you for that analysis, I will ping it back to the wrapper developer.

**Comment by EasiestSoft** [comment] 2019-12-16 02:42
This issue can be solved by specifying calling conversion to `cdecl` in Nim:
https://gitlab.com/define-private-public/stb_image-Nim/issues/8#note_258651948

**Comment by nothings** [comment] 2019-12-16 09:33
Thanks, closing this.

**Closed by nothings** 2019-12-16 09:33 UTC
