### ISSUE TITLE
stb_image_write produces invalid PNG file when forcing filter mode 0

### ISSUE THREAD

**Issue by dictoon** [nothings/stb#948] opened 2020-04-03 10:08 UTC
I'm using stb_image_write v1.14 (the latest official version at the time of writing) on Windows.

My application writes a series of 2048x2048 RGBA images to disk using stb_image_write. By default stb_image_write takes too long to write those images (about 25 seconds per image with a debug build). To alleviate the problem I set `stbi_write_force_png_filter` to 0 (I'm more interested in writing speed than size on disk).

Most of these images are written correctly, but for some reason one of them isn't. The file is too big to be attached to this issue but you can find it here:
https://www.dropbox.com/s/tdwetg5i90lpe8p/stb_image_write_bug.zip?dl=0

Here is the output of ImageMagick's identify tool on this image:
```
identify.exe: IDAT: chunk data is too large `stb_image_write_bug.png' @ error/png.c/MagickPNGErrorHandler/1711.
identify.exe: CorruptImage `stb_image_write_bug.png' @ error/png.c/ReadPNGImage/4270.
```

Photoshop manages to open it just fine but other applications such as XnView don't.

stb_image_write produces a valid file if `stbi_write_force_png_filter` is left to its default value.

**Comment by dictoon** [comment] 2020-04-03 10:31
Compression mode vs performance on 4096x4096 RGBA images:
```
Mode   Size (KB)   Time (s)
0      65035       3.654
1      60214       15.726
2      60283       15.547
3      56600       21.401
4      55824       27.665
```

**Comment by nothings** [comment] 2020-04-03 10:42
see https://github.com/nothings/stb/blob/master/stb_image_write.h#L20

```
   This library is designed for source code compactness and simplicity,
   not optimal image file size or run-time performance.
```

**Comment by dictoon** [comment] 2020-04-03 10:52
Oh yes I know :)

I like the simplicity and I'm satisfied with the performances without any compression. The point of this bug report is correctness, not performance.

**Comment by rygorous** [comment] 2021-07-04 04:27
That's this check in libpng: https://github.com/glennrp/libpng/blob/libpng16/pngrutil.c#L3181

Looks like the issue is that the "compressed" data emitted by stbi_zlib_compress without filtering (for this image) is sufficiently larger than the uncompressed data to trip this sanity check. To fix this, stbi_zlib_compress needs to check whether it ended up expanding the data and emit uncompressed blocks if so.

**Comment by nothings** [comment] 2021-07-04 04:35
given that this only happens if you use stbi_write_force_png_filter at non-default, I don't think it really needs fixing. If it can be done easily, then sure.

To be clear, I agree it sucks that it's so slow without it, but given that the file is technically valid and it's a non-default config and that stb_image_write is meant for quick-and-dirty uses, I just don't think it's a priority. We'll take a PR that fixes it but I don't expect us to put work into it.

**Comment by rygorous** [comment] 2021-07-04 07:11
I'm not so sure that it only happens at non-default; I think it only happens on large images that compress sufficiently poorly, the filter thing makes it easier to encounter but should not be required to trigger this problem.

**Comment by rygorous** [comment] 2021-07-07 09:33
This is now fixed in the dev branch, will ship in the next release.

**Closed** 2021-07-12 00:13 UTC
Labels: 1 stb_image_write, 2 bug, 5 merged-dev
