### ISSUE TITLE
[stb_image.h]  BMP file RGB16 convert error

### ISSUE THREAD

**Issue by BOGUENSONG** [nothings/stb#873] opened 2020-01-10 07:20 UTC
Hello, I have a problem about BMP convert.
if i convert **RGB24** BMP, i receive image success!
but, if i convert **RGB16** BMP, i receive moved image

this is original file
![image](https://user-images.githubusercontent.com/45163272/72133421-b286b280-33c4-11ea-8a7a-c90d17013d6b.png)

this is convert file
![image](https://user-images.githubusercontent.com/45163272/72133456-d21ddb00-33c4-11ea-8803-4b77181c1176.png)

can i solve this problem?

**Comment by nothings** [comment] 2020-01-10 09:50
duplicate of #870

**Closed by nothings** 2020-01-10 09:50 UTC
