### ISSUE TITLE
Minor - possible loss of data warnings (false positives)

### ISSUE THREAD

**Issue by leok7v** [nothings/stb#334] opened 2016-07-23 21:59 UTC
On warning level 4 with msvc2012 got some little noise in warnings:

May be
  stbi__get16le should return stbi__uint16 to follow the same convention as:
stbi_uc stbi__get8?

```
stb_image.h(4503): warning C4244: '=' : conversion from 'int' to 'stbi__uint16', possible loss of data
stb_image.h(5082): warning C4244: 'initializing' : conversion from 'int' to 'stbi__uint16', possible loss of data
stb_image.h(5089): warning C4244: '=' : conversion from 'int' to 'stbi_uc', possible loss of data
stb_image.h(5090): warning C4244: '=' : conversion from 'int' to 'stbi_uc', possible loss of data
stb_image.h(5091): warning C4244: '=' : conversion from 'int' to 'stbi_uc', possible loss of data
```

**Comment by nothings** [comment] 2018-01-29 15:06
Need to dig into the source history to see which things these line numbers referred to, and I'm too lazy to do so today, so this is going to sit and wait longer. Sorry.

**Comment by rygorous** [comment] 2021-07-03 06:02
Can't reproduce these with current VC++ and current stb_image so I'm assuming this got resolved in the meantime.

**Closed by rygorous** 2021-07-03 06:02 UTC
Labels: 1 stb_image, 2 bug, help wanted
