### ISSUE TITLE
Calculus of scanline is multiplying X twice

### ISSUE THREAD

**Issue by ignotion** [nothings/stb#655] opened 2018-09-10 17:18 UTC
https://github.com/nothings/stb/blob/e6afb9cbae4064da8c3e69af3ff5c4629579c1d2/stb_image_write.h#L697

If what's pretended is going to the scanline i, that sentence is mutiplying twice by X so it goes rapidly out of rance, if I'm correct it should be:

comp*x*(stbi__flip_vertically_on_write ? y-1-i : i)
size of pixel * pixels on X * i [or y-1-i]

**Comment by LysanderGG** [comment] 2018-09-11 00:13
See PR #585

**Comment by rygorous** [comment] 2018-10-23 02:14
Duplicate of #567.

**Closed by rygorous** 2018-10-23 02:14 UTC
