### ISSUE TITLE
JPG decoder - Ycck and Cmyk color spaces

### ISSUE THREAD

**Issue by photopea** [nothings/stb#969] opened 2020-05-22 13:27 UTC
When the following JPG images are decoded by your library, the colors are different, than what is shown by other JPG viewers: https://imgur.com/uXwoJ4Y

The problem is in your formulas of converting Ycck and Cmyk to RGB. Could you please switch to the following formulas?  https://pastebin.com/fqxnb60p

![IntWarp](https://user-images.githubusercontent.com/15955558/82672395-99c6bd00-9c40-11ea-8c3f-5729fd7d6e51.jpg)
![Poster design_Final](https://user-images.githubusercontent.com/15955558/82672400-9b908080-9c40-11ea-8bf3-803c44e98b79.jpg)

**Comment by rygorous** [comment] 2021-06-29 01:06
Sorely tempted to remove CMYK support entirely since it's essentially out of scope for stb_image to begin with and the fact that it took 13 years for anyone to notice that it doesn't even work right seems good experimental evidence that it's not an important feature.

**Comment by jpcy** [comment] 2021-06-29 03:00
For comparison, libjpeg-turbo doesn't convert CMYK to RGB.
https://sourceforge.net/p/libjpeg-turbo/patches/15/

**Comment by photopea** [comment] 2021-06-29 07:01
But why do other image viewers (and web browsers) open these JPGs correctly, if they are not considered to be standard JPG files?

**Comment by nothings** [comment] 2021-07-02 14:58
I don't know what the imgur link is showing. It appears Chrome produces the image on the left, and Firefox produces the image on the right. stb_image produces the same result as Firefox, which is the classic conversion which just maps the full gamut of CMYK to the full gamut of RGB, rather than trying to match the colorspaces accurately.

I tried searching for some of the magic numbers in your pastebin to see where these formulas came from, and while I got dozens of hits in open source codebases, I couldn't find any origin or explanation for them. Presumably somebody came along at some point and said the "classic conversion" was all wrong and we should do something else.

But without some reasonable explanation for it, and given that Firefox and other software produces the same results as stb_image, I think it's better to leave it as it is.

**Comment by photopea** [comment] 2021-07-02 15:25
The JPG image has an ICC color profile attached. It describes a way how to convert color values in a file into a La*b* color space (and from that, you can convert e.g. to sRGB color space).

I think there exists some popular CMYK space, that is used in 90% of cases (including our JPG), and the "magic formulas" are related to that color space (they are a simplification of the ICC profile). I think it is better to use these "magic formulas" than to implement a whole ICC processor.

**Comment by nothings** [comment] 2021-07-02 17:40
But if only SOME cmyk files include an ICC profile that corresponds to the "magic formulas", then it doesn't really solve the problem to apply those formulas to ALL cmyk files. So that's another reason not to do this, on top of the fact that stb_image behavior matches Firefox anyway.

So: not a bug.

**Closed by nothings** 2021-07-02 17:40 UTC
Labels: 1 stb_image, 2 bug, needs changes

**Comment by photopea** [comment] 2021-07-02 22:45
The formula will work correctly for 99% of CMYK JPG files. You should not look at the browser, which is used by 5% of the market (and decreasing). Look at the browser, which is used by the majority of the market.

You did a great job with this library. Sometimes, extra 10% of work will get you 10x more users. I truly believe, that implementing it would take you less time than reading and replying to my comments.

**Comment by rygorous** [comment] 2021-07-02 23:06
We don't care about reaching "10x more users". stb_image is a (relatively) minimalist image loader with a limited feature set. We are completely fine with many use cases being outside of that feature set.
