### ISSUE TITLE
stb_sprintf: warning about unused variable

### ISSUE THREAD

**Issue by stefano-zanotti** [nothings/stb#1089] opened 2021-02-02 15:12 UTC
Compiling STB sprintf with STB_SPRINTF_NOFLOAT, GCC raises a warning:
`stb_sprintf.h:529:23: warning: variable 'dp' set but not used [-Wunused-but-set-variable]`

The variable is this one:
https://github.com/nothings/stb/blob/master/stb_sprintf.h#L529
used in vsprintfcb, set by various switch cases, but never actually used when STB_SPRINTF_NOFLOAT is defined. Even a branch guarded by '#ifdef STB_SPRINTF_NOFLOAT' sets it to 0, without ever reading from it.
The simple fix is to add
`(void)dp;`
here:
https://github.com/nothings/stb/blob/master/stb_sprintf.h#L608
You could also remove the assignment dp=0 in that switch case; anyway, the variable is assigned to in other non-float-related cases, so this alone wouldn't be enough to prevent the warning.
stb_sprintf.h doesn't have an STB*_UNUSED macro yet.

**Comment by rygorous** [comment] 2021-07-07 10:21
Duplicate of #986, closing.

**Closed by rygorous** 2021-07-07 10:21 UTC
Labels: 1 stb_sprintf, 2 warning, code quality
