### ISSUE TITLE
stb_vorbis: Seeking to start of file makes stream unusable

### ISSUE THREAD

**Issue by DeRoquefeuille** [nothings/stb#580] opened 2018-03-14 16:59 UTC
I'm having a problem with looping a file by seeking to the start of it as soon as the end is reached.

After calling stb_vorbis_seek_start() for a stream, all subsequent calls to stb_vorbis_get_samples_short_interleaved() fail as vorbis_decode_initial() dos not detect the vorbis capture pattern. As far as I can tell with my limited knowledge of the library this happens because stb_vorbis_seek_start seeks to the first audio page, which does not include the capture pattern.

The same problem occurs when using stb_vorbis_seek_frame or stb_vorbis_seek with a low sample/frame number, as this ultimately also sets the stream to the first audio page via stb_vorbis_seek_start.

Exchanging the line
`set_file_offset(f, f->first_audio_page_offset);`
with
`set_file_offset(f, 0);`
in stb_vorbis_seek_start() fixes the issue for me. However as my knowledge of the lib is quite limited, I have no idea how much extra work this incurrs.

**Comment by philipguin** [comment] 2019-09-30 23:10
I'm also experiencing the problem with a low sample/frame number... attempting the fix is more complicated, however, since I'm using STB via LWJGL bindings. I could recompile it and test, but it's quite the hassle. I'm also not sure if the fix, when implemented, provides the correct behavior.

**Comment by dougallj** [comment] 2019-10-01 00:39
Does anyone who's had this issue have a reproducing vorbis file they could share? (I'm guessing if the file fails [tests/vorbseek](https://github.com/nothings/stb/blob/master/tests/vorbseek/vorbseek.c) it would be file specific - otherwise specific api usage or seek patterns might be required to reproduce?)

**Comment by philipguin** [comment] 2019-10-01 01:09
Here you go. The file was generated with Ableton as a WAV, converted to Vorbis with LameXP (with extra --mixdown flag, if it matters. Don't have other settings on me atm, but the rest are basically defaults as I recall.)

[AmbiguouslyYours_DrumsDelay.zip](https://github.com/nothings/stb/files/3673926/AmbiguouslyYours_DrumsDelay.zip)

Usage pattern from STBVorbis perspective goes like:

```
stb_vorbis_open_filename
stb_vorbis_get_info
for (xxx)
{
    for (xxx)
    {
        for (xxx)
            stb_vorbis_get_samples_short_interleaved( someBuffer )

        // play samples in someBuffer over corresponding time frame
    }

    stb_vorbis_seek // failing line
}
```

After converting times to samples at 48k Hz, starting at the 0.0 second mark (with or without a seek call), then seeking to the 0.2 second mark, fails every time. Seeking to the 0.25 second mark does *not* fail, however.

My test case is actually tracking the number of samples retrieved and seeking back after hitting a certain number (and we don't ask for any more samples than we use.) I don't think it'll matter (it repros whether I'm retrieving exactly one second or an entire minute's worth of samples), but I thought I'd mention it jic.

**Comment by dougallj** [comment] 2019-10-01 03:06
Looks like I can reproduce an issue with that file, thanks! I'll hopefully have time to diagnose properly soon.

The following repro code prints error 37 (`VORBIS_seek_failed`):

```c
#include <assert.h>
#include <stdio.h>
#include "stb_vorbis.c"

int main(int argc, char **argv) {
   int error;
   stb_vorbis *v = stb_vorbis_open_filename("AmbiguouslyYours_DrumsDelay.ogg", &error, NULL);
   assert(v);
   printf("seek %s\n", stb_vorbis_seek(v, 9324) ? "success" : "failure");
   printf("error: %d\n", stb_vorbis_get_error(v));
   return 0;
}
```

**Comment by dougallj** [comment] 2019-10-01 07:03
Philip's issue seems to be caused by a check for `f->current_loc > sample_number` added at the end of `seek_to_sample_coarse` ([line 4763](https://github.com/nothings/stb/blob/5c98e6564ba74d5a6e97004dd8730a69e9e7b6e6/stb_vorbis.c#L4763-L4764)). This would be correct, but the `sample_number` argument is changed during the body of the function.

Proposed fix is to make `sample_number` immutable. The changes are at https://github.com/dougallj/stb/commit/2abc5c6ced37e2d70a5e7401dbbb9cfc5700995e, but I'd like to test thoroughly before creating a PR. (There's another fix for a theoretical performance problem seeking near the end of a file with unprecedentedly huge pages on that branch too.)

The bad news is that I suspect this isn't the issue reported. That code isn't involved in `stb_vorbis_seek_start`. @DeRoquefeuille any chance you still have a file that can repro this issue?

**Comment by DeRoquefeuille** [comment] 2019-10-01 07:39
I encountered the bug with multiple files from different sources. 

One file I recall testing was [this Ogg Vorbis example file] (https://commons.wikimedia.org/wiki/File:Example.ogg) from Wikipedia.

**Comment by dougallj** [comment] 2019-10-01 11:08
That works to repro, thanks! Sorry I didn't see this issue sooner. I think #682 is a duplicate of this (and has another good test file). Somehow, in all the files I'd tested, the initial pages that contain the header packets didn't contain audio packets. When they do, it breaks quite a few assumptions.

Using `set_file_offset(f, 0)` shouldn't incur much extra work, so my proposed fix (https://github.com/dougallj/stb/commit/7c4eb44a636ab398b1aea872e4f5792ad66d7706) uses that technique, but only on files with audio packets in headers pages. (I'd still like to do some more thorough testing, but hopefully that'll do it)

**Comment by rygorous** [comment] 2021-07-05 02:39
Fix was merged in Oct 2019, closing this issue.

**Closed by rygorous** 2021-07-05 02:39 UTC
Labels: 1 stb_vorbis, 2 bug
