### ISSUE TITLE
load bmp 24b failed

### ISSUE THREAD

**Issue by xfcanyue** [nothings/stb#1120] opened 2021-03-27 07:34 UTC
failed in stbi__bmp_parse_header while hsz = 40, bpp=24.

**Comment by nothings** [comment] 2021-03-27 08:06
You can just link to the function instead of pasting the whole thing: https://github.com/nothings/stb/blob/master/stb_image.h#L5275

Anyway, put a breakpoint in stbi__err so you can see which path is failing, or provide an image that is failing.

**Comment by xfcanyue** [comment] 2021-03-27 15:00
stbi__bmp_load will return stbi__errpuc("bad offset", "Corrupt BMP");

in this url, 
https://github.com/nothings/stb/blob/master/stb_image.h#L5275, 
line 5299, No chance to deal with bpp=24 .

stb_image - v2.08  it was working ok,  but today i try to upgrade to stb_image - v2.26, I found that the bitmap could not be loaded.
16 bits bmp or 256 bits bmp can be loaded, 24 bits bmp failed.

**Comment by xfcanyue** [comment] 2021-03-27 15:45
[Uploading images.zip…](my test file)

**Comment by xfcanyue** [comment] 2021-03-27 15:46
[images.zip](https://github.com/nothings/stb/files/6215931/images.zip)

**Comment by nothings** [comment] 2021-03-27 16:03
bmp24.bmp from that zip loads fine for me.

1. make sure that stb_image is the problem. if you change nothing else but switch back to your old v2.08 does it work again?
2. if it's definitely stb_image, what platform and compiler are you using and do you have any unusual settings?

**Comment by nothings** [comment] 2021-03-27 16:06
Oh, I believe this is fixed in #1102. Please note that you said line 5299 but it's actually line 5399 so I misunderstood what the error was.

**Comment by xfcanyue** [comment] 2021-03-28 01:02
yes. 
line 5399: return stbi__errpuc("bad offset", "Corrupt BMP"),  when calling stbi_load_from_memory.
it is important for DirectUI to loading bmp.

**Comment by rygorous** [comment] 2021-07-02 00:47
Duplicate of #994.

**Closed by rygorous** 2021-07-02 00:47 UTC
Labels: 1 stb_image, 2 bug w/ file
