### ISSUE TITLE
Does not support Unicode file paths on Windows using MinGW/gcc

### ISSUE THREAD

**Issue by EasiestSoft** [nothings/stb#857] opened 2019-12-20 01:27 UTC
`Can't fopen` exception when loading or saving an image

**Comment by nothings** [comment] 2019-12-20 05:43
How is this different from #729?

**Comment by EasiestSoft** [comment] 2019-12-20 06:11
It's the same thing. This issue makes it clear that ` stb does not support Unicode file paths on Windows using MinGW / gcc`, and #729 locates the relevant source code

**Comment by EasiestSoft** [comment] 2019-12-20 06:12
> 
> 
> How is this different from #729?



> 
> 
> How is this different from #729?

It's the same thing. This issue makes it clear that ` stb does not support Unicode file paths on Windows using MinGW / gcc`, and #729 locates the relevant source code

**Comment by nothings** [comment] 2019-12-20 06:30
Closed duplicate of #729.

**Closed by nothings** 2019-12-20 06:30 UTC

**Comment by Photosounder** [comment] 2020-05-26 15:58
It's still not fixed if I'm not mistaken and it's also annoying that it doesn't default to UTF-8. Maybe consider just using something like this to spare everyone headaches: https://github.com/Photosounder/fopen_utf8/
