### ISSUE TITLE
write_hdr row calculation causing crash

### ISSUE THREAD

**Issue by oconnorkg** [nothings/stb#602] opened 2018-04-30 17:24 UTC
Line 697 of std_image_write.h has a typo:-
`stbiw__write_hdr_scanline(s, x, comp, scratch, data + comp*x*(stbi__flip_vertically_on_write ? y-1-i : i)*x);`

Removing the *x at the end of the line fixes it.

**Comment by tviksand** [comment] 2018-05-03 08:34
Should be fixed in pullreq #604

**Comment by rygorous** [comment] 2018-10-23 03:08
Duplicate of #567.

**Closed by rygorous** 2018-10-23 03:08 UTC
