### ISSUE TITLE
stb_vorbis - stb_vorbis_open_file always returns error code 3 (outofmem)

### ISSUE THREAD

**Issue by Mitch-Muscle-Man-Sorenstein** [nothings/stb#1021] opened 2020-08-25 02:40 UTC
I have just implemented the latest version of stb_vorbis into my project, only to find that stb_vorbis_open_file was always erroring. Printing the error code result always returned error code 3, but I knew the code worked before. Going back to an older version of stb_vorbis I had on me (August 2019?), it worked fine there. Unless something was changed with how stb_vorbis functions since then, this seems to be a bug.

**Comment by akien-mga** [comment] 2020-09-09 15:14
Might be the bug that #1005 fixes, can you give it a try to confirm?

**Comment by vitamin-caig** [comment] 2020-11-06 11:15
Found the same error, but from another place. Was introduced between e6afb9cbae4064da8c3e and b42009b3b9d4ca35bc703f5310eedc74f

[out_of_memory.ogg.zip](https://github.com/nothings/stb/files/5500925/out_of_memory.ogg.zip)

**Comment by ITotalJustice** [comment] 2020-12-11 20:27
hi, i had the same issue today. for me it was caused by the user_comments field being NULL as the size for it was 0. I'm not too familiar with user comments, but maybe they are optional? removing the null check fixes it for me. this check was added in #989

**Comment by anthofoxo** [comment] 2021-01-15 22:49
Do you have any example code and an audio file in which is occurs. If so i can do some digging to see if its a similar fix in my other pr  #1064

**Comment by kcgen** [comment] 2021-06-24 00:07
PR https://github.com/nothings/stb/pull/1005 introduced a regression by assuming that some number of ser comments are always present. 

If there are no comments, then this happens:

``` c++
f->comment_list_length = get32_packet(f);  <--- this is zero (no comments)
f->comment_list = (char**)setup_malloc(f, sizeof(char*) * (f->comment_list_length)); <--- malloc(0) returns NULL
```

Therefore, the lack of user comments will mean `f->comment_list = ` is assigned `NULL`.

PR 1005 added this code:

``` C++ 
if (f->comment_list == NULL)                     return error(f, VORBIS_outofmem);
```

Which now always triggers.

Here's an example OGG file without user comments:

[track02.ogg.zip](https://github.com/nothings/stb/files/6705427/track02.ogg.zip)

A fix for this is to replace the above `if` check with:

``` c++
if (f->comment_list_length > 0 && f->comment_list == NULL)
    return error(f, VORBIS_outofmem);
```

**Comment by nothings** [comment] 2021-07-02 14:00
Fixed this bug finally. Thank you for reporting, my apologies for how long it took to address.

**Closed by nothings** 2021-07-02 14:00 UTC
Labels: 1 stb_vorbis, 2 bug
