### ISSUE TITLE
Wrong access to HDR images in stb_image_write

### ISSUE THREAD

**Issue by honzasp** [nothings/stb#619] opened 2018-06-02 17:53 UTC
In `stbi_write_hdr_core`, when computing the offset for the current scanline in the call to `stbiw__write_hdr_scanline()`, the offset is incorrectly multiplied by `x` (the image width) twice, so the function will access invalid memory:

      stbiw__write_hdr_scanline(s, x, comp, scratch, data + comp*x*(stbi__flip_vertically_on_write ? y-1-i : i)*x);

should probably be

    stbiw__write_hdr_scanline(s, x, comp, scratch, data + comp*(stbi__flip_vertically_on_write ? y-1-i : i)*x);

**Comment by installgentoo** [comment] 2018-06-03 19:40
Yes this is a bug that crashes the project, i just saw this very bug while debugging crash in this very header.

**Comment by zhabkab** [comment] 2018-06-29 20:14
I also encountered this bug, but I found an older version of the lib had the correct code.  It seems like there was an extra multiplication which makes the offset far too large.

**Comment by rygorous** [comment] 2018-10-23 02:15
Duplicate of #567.

**Closed by rygorous** 2018-10-23 02:15 UTC
