### ISSUE TITLE
stb_image_write.h v1.09: Access violation when writing a jpeg at 1680x1050 resolution.

### ISSUE THREAD

**Issue by maraakate** [nothings/stb#592] opened 2018-04-08 17:30 UTC
Hi STB,

I've found that when trying to write a jpeg at 1680x1050 resolution Visual Studio will crash out with an Access Violation error and points to the following function: stbiw__jpg_processDU

The exact line it is unhappy with is r = imageData[p+0];
p = -10080

The parameters sent to stbi_write_jpeg:
	stbi_flip_vertically_on_write(1);
	bSuccess = stbi_write_jpg(checkname, grab_width, vid.height, 3, buffer, 100);

I am able to write out a PNG just fine at the same resolution with stb.

Hope this helps and thanks for all your hard work!
Frank

**Comment by zao** [comment] 2018-04-08 18:30
Reproduced this with a fresh project off master and a buffer of the accurate dimensions.
Only happens for heights that are not multiples of 8, which 1050 notably is.
Over-allocating storage around the image results in a successful write, but the file ends up larger in file size than it should be, which hints to reading unexpected data.

**Comment by nothings** [comment] 2018-04-08 21:39
Oh yeah, this is on me then, I wrote the flip_vertically support and didn't thoroughly test it. Don't worry about it further @DanielGibson.

**Comment by DanielGibson** [comment] 2018-04-08 22:06
Ok, no worries :)

I guess the
```c
                  if(row >= height) {
                     p -= width*comp*(row+1 - height);
                  }
```
part must also be adjusted for `stbi__flip_vertically_on_write` somehow

**Comment by DanielGibson** [comment] 2018-04-08 22:49
however, I find the following code more readable, and it's even shorter:
```c
                  float r, g, b;
                  int p;
                  if(row < height) {
                     p = (stbi__flip_vertically_on_write ? (height-1-row) : row)*width*comp;
                  } else {
                     // row >= height => use last input row (=> first if flipping)
                     p = stbi__flip_vertically_on_write ? 0 : ((height-1)*width*comp);
                  }
                  // if col >= width => use pixel from last input column
                  p += ((col < width) ? col : (width-1))*comp;

                  r = imageData[p+0]; // etc, no changes from here on
```

**Comment by maraakate** [comment] 2018-04-08 22:49
What's weird though is writing a PNG has no problems for me at 1680x1050.

**Comment by nothings** [comment] 2018-04-08 22:55
There's nothing weird about that, flip_vertically_on_write is handled internally by each of the 5 file formats, rather than being a single systematic approach, so it's totally separate code in each case.

**Comment by maraakate** [comment] 2018-04-08 22:56
OK, yeah @DanielGibson just informed me about that as well.  I didn't follow PNG's code, my apologies.

**Comment by DanielGibson** [comment] 2018-04-08 23:03
btw, I tested the code I posted with 2560x1600, 1680x1050, 8x8 and 5x5 pixels, flipped and unflipped, and I think it looked good every time (some of the pixel colors in the 8x8 and 5x5 cases looked a bit off, but I think that's due to jpg)

**Comment by DanielGibson** [comment] 2018-04-08 23:29
PR with patch can be found at https://github.com/nothings/stb/pull/593 - would be nice if someone could test it, just to be double-sure :)

**Comment by maraakate** [comment] 2018-04-08 23:32
Just tested and works OK for me.

**Comment by DanielGibson** [comment] 2019-02-08 04:25
this can be closed as my fix has been merged :)

**Closed** 2019-02-08 04:49 UTC
Labels: bug, stb_image_write
