### ISSUE TITLE
stb_image Unused variable warning when -Wunused-variable active.

### ISSUE THREAD

**Issue by cliffordslocombe** [nothings/stb#1080] opened 2021-01-23 21:44 UTC
The `STBI_REALLOC_SIZED` macro does not use the `oldsz` argument and in `stbi__load_gif_main` the `out_size` and `delays_size` variables passed as `oldsz` are not otherwise used (initialised and assigned but never read).  

When `-Wunused-variable` or any other `-W` switch that implies it (such as `-Wall`).  A warning is issued.  If `-Werror` is used, then compilation fails.  These are all reasonable options for a developer to use.

Suggest:

```
int out_size = 0; STBI_NOTUSED(out_size) ;
int delays_size = 0; STBI_NOTUSED(delays_size) ;
```

**Comment by randomMesh** [comment] 2021-01-24 23:10
There is already a pull request for this: #1016

**Comment by rygorous** [comment] 2021-06-29 00:53
Yes this is a dupe of #1016, will close this one.

**Closed by rygorous** 2021-06-29 00:53 UTC
