### ISSUE TITLE
stb_image: left shift of negative value

### ISSUE THREAD

**Issue by guillaumechereau** [nothings/stb#617] opened 2018-05-31 07:21 UTC
I think similar "bugs" have been fixed before, but I still get some warnings from usan on linux when opening jpeg files:

    stb_image.h:2022:29: runtime error: left shift of negative value -337
    stb_image.h:2059:43: runtime error: left shift of negative value -1
    stb_image.h:2077:63: runtime error: left shift of negative value -2

**Comment by dhuber23b** [comment] 2018-07-24 20:31
I am seeing the same errors.  Do you know when they were fixed or how?

**Comment by dhuber23b** [comment] 2018-07-24 21:02
I have a temporary workaround.  I will create a pull request after I hit this deadline.
[signed_shift_patch.txt](https://github.com/nothings/stb/files/2225407/signed_shift_patch.txt)

**Comment by rygorous** [comment] 2018-10-23 02:58
Will fix this for the next release.

**Comment by dhuber23b** [comment] 2018-11-03 02:19
Great, thanks.

**Comment by rygorous** [comment] 2021-07-03 06:11
Oops, ended up fixing the duplicate of this issue #1097. Either way, the fix is actually in the dev branch now and really will be in the next version; closing this duplicate.

**Closed by rygorous** 2021-07-03 06:11 UTC
Labels: 1 stb_image, code quality
