### ISSUE TITLE
Assertion failed but the program runs correctly

### ISSUE THREAD

**Issue by HenryAWE** [nothings/stb#635] opened 2018-07-06 08:07 UTC
https://github.com/nothings/stb/blob/e6afb9cbae4064da8c3e69af3ff5c4629579c1d2/stb_truetype.h#L3046

When I try to render the Chinese character ‘夫',the program crushed under Debug mode.However,everything looks ok under release mode.

I think this assertion is unnecessary.

**Comment by zao** [comment] 2018-07-07 07:54
Could you please tell us a bit more about which font you are using and which functionality in stb_truetype you're calling?

A small standalone test program that produces the bug might be helpful, I cannot seem to trigger the assertion with SimSun or Yu Gothic, doing a `stbtt_GetCodepointBitmap` for 25.0f pixel height.

**Comment by nothings** [comment] 2018-07-07 08:01
To clarify @zao's comment, it's possible that deleting the assert is the correct answer, but I'd much prefer to trigger the assert and look at what's going on so I can see what exactly is going on before deleting it, so being able to reproduce the assert triggering is necessary to move forward.

**Comment by HenryAWE** [comment] 2018-07-07 09:39
@zao I used the msyh.ttf (微软雅黑 in Chinese) as font,and the program triggered the assertion when I called the function **stbtt_GetCodepointBitmap**

**Comment by HenryAWE** [comment] 2018-07-07 11:58
@nothings the return value of `stbtt_ScaleForPixelHeight(info,100.0f);`

**Comment by nothings** [comment] 2018-07-07 13:10
Thanks, I will take a look.

**Comment by zao** [comment] 2018-07-08 02:01
I cannot reproduce this on VS2017 with current master nor an old 1.12, having tried Windows 10 1803's `msyh.ttc`, Windows 7's `msyh.ttf` version 6.02, and some older `msyh.ttf` version 0.75 I found on GitHub.

My test program is as follows:
```c
#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

#include <assert.h>
#include <stdio.h>

int
main()
{
    FILE* fh;
    size_t cb;
    unsigned char* ttf_data;
    stbtt_fontinfo font;
    int const ch = 0x592b;
    int w, h;
    unsigned char* bitmap;
    int row, col;

    fh = fopen("msyh.ttf", "rb");
    assert(fh);
    fseek(fh, 0, SEEK_END);
    cb = ftell(fh);
    fseek(fh, 0, SEEK_SET);

    ttf_data = malloc(cb);
    assert(ttf_data);
    fread(ttf_data, 1, cb, fh);
    fclose(fh);

    stbtt_InitFont(&font, ttf_data, stbtt_GetFontOffsetForIndex(ttf_data, 0));
    bitmap = stbtt_GetCodepointBitmap(&font,
                                      0.0f,
                                      stbtt_ScaleForPixelHeight(&font, 100.0f),
                                      ch,
                                      &w,
                                      &h,
                                      NULL,
                                      NULL);
    assert(bitmap);
    for (row = 0; row < h; ++row) {
        for (col = 0; col < w; ++col) {
            printf("%c", bitmap[row * w + col] ? 'X' : '-');
        }
        printf("\n");
    }

    free(bitmap);
    free(ttf_data);
    return 0;
}

```

**Comment by rygorous** [comment] 2018-10-23 02:50
Apparently, can't repro and the original reporter hasn't provided any more details about what version of the TTF results in the error, so I'm closing this for now.

**Closed by rygorous** 2018-10-23 02:50 UTC
