### ISSUE TITLE
stb_vorbis_open_filename causes VORBIS_outofmem error

### ISSUE THREAD

**Issue by anthofoxo** [nothings/stb#1063] opened 2020-12-16 21:03 UTC
I'm using stb_vorbis to load ogg files for playback using portaudio. Some audio files work fine loading in without a problem, but others when loading cause an outofmem error to occur, even when its smaller than the others. Its about 70kb in size.

`stb_vorbis* vorbisStream;

{
	int error = 0;
	vorbisStream = stb_vorbis_open_filename("res/track00.ogg", &error, nullptr);

	// load fine using music.ogg but return error code 3 (not enough memory) on track00.ogg (is about 65kb) which is smaller than music.ogg
	// track00.ogg was exported via audacity using the lowest quality setting
	if (error != VORBIS__no_error)
	{
		__debugbreak();
	}
					
}`

This is the current commit i am on
https://github.com/anthofoxo/wave/tree/01abcdea304cbcd60c8290d0b6a5e651245a388a

The loading code is in projects/wave/src/Application.cpp on line 89
The audio file is located in projects/wave/res/track00.ogg

**Comment by anthofoxo** [comment] 2020-12-16 21:16
Update: after fooling around a bit this only seems to fail when i export from audacity without entering any metadata upon exporting

**Comment by anthofoxo** [comment] 2020-12-16 23:13
I have found the problem in the code, i will make a pull request with the changes soon

**Comment by bsdunx** [comment] 2020-12-22 12:28
> I have found the problem in the code, i will make a pull request with the changes soon

This should at the least guard the call to `setup_malloc` predicating on `f->comment_list_length > 0`

**Comment by anthofoxo** [comment] 2020-12-25 23:52
> > I have found the problem in the code, i will make a pull request with the changes soon
> 
> This should at the least guard the call to `setup_malloc` predicated on `f->comment_list_length > 0`

I'll look into the details and ill work on that. I'll update the branch with the changes sometime this evening

**Comment by nothings** [comment] 2020-12-26 00:11
there are already multiple PRs for this, you might check those

**Comment by rygorous** [comment] 2021-06-29 01:11
This is a dupe of the comment issue, closing this.

**Closed by rygorous** 2021-06-29 01:11 UTC
