### ISSUE TITLE
Global versioning?

### ISSUE THREAD

**Issue by lasote** [nothings/stb#555] opened 2018-02-05 14:40 UTC
Hi,

I'm creating a [Conan](conan.io) package for SFML and internally is requiring `stb_image.h` and  `stb_image_write.h`. I'm trying to create a package for any dependency of SFML. 

Should I create a different package for each header in this repository? I've seen that every header has its own versioning, but feels a little overkilling. I suppose that you have created a single repository for the same reason.

Have you considered to tag the global repository with a version? 

Thanks!

**Comment by nothings** [comment] 2018-02-11 19:36
Duplicate of https://github.com/nothings/stb/issues/359 I think.

**Closed by nothings** 2018-02-11 19:36 UTC
