### ISSUE TITLE
stb_image allow user to supply a separate callback for allocating the result data.

### ISSUE THREAD

**Issue by ratchetfreak** [nothings/stb#435] opened 2017-03-14 17:08 UTC
This would be handy for example when you want to use an api that will give you a pointer to the memory to put the data into (for example mapping an opengl PBO). So you can avoid the memcpy. Additionally some apis require an aligned row stride (or you may want to put the image into an atlas). 

The callback could have a signature like

```C
typedef struct allocated_image{
    void *memory;
    int row_stride;
    void *user_context;
} allocated_image;

void allocate_result_buffer(image_info info, allocated_image *result, void *user_context);
```

The `void* user_context` passed in is there to get a reference to any objects needed for the other api and in case the thread-safety issue ever gets resolved and globals would cause issues. The one in the result struct is there to allow the user code to keep track of underlying api object associated with the memory.

**Comment by nothings** [comment] 2017-03-14 17:15
This is effectively a dupe of https://github.com/nothings/stb/issues/58 which proposes passing in the memory to decode into rather than getting a callback. (You can use the 'info' function to get the size first, then pre-allocate it through whatever means you want,.)

**Closed by nothings** 2017-03-14 17:15 UTC
