### ISSUE TITLE
stb_truetype.h: Undefined function / undefined functions warnings

### ISSUE THREAD

**Issue by jstimpfle** [nothings/stb#516] opened 2017-11-03 07:31 UTC
My gcc gives me warnings when using stb_truetype.h from commit 555efbedfc00f038c882bf6097e139864a3580e2

1. Declared but undefined function stbtt_MakeCodepointBitmapSubpixelPrefilter()

2. When compiling with SBTT_STATIC turned on, I get a lot of unused functions warnings, which makes static compilation unusable for me. Here's a quick fix which works for gcc and clang:

```
-#define STBTT_DEF static
+#define STBTT_DEF static __attribute__((unused))
```
But I suspect a good solution needs to detect if this syntax is available.

**Comment by kphillisjr** [comment] 2017-11-17 16:43
@jstimpfle I submitted a patch to fix this issue correctly. The warning you saw about unused/undefined functions is about a function that has yet to be fully implemented. A fix that implements the missing function is found in pull #517. Although I have yet to determine if this new function works as intended.

**Comment by nothings** [comment] 2018-01-29 13:12
(1) is merged and will be in the next release.

I still don't know of a good solution to (2)

**Comment by rygorous** [comment] 2021-07-07 09:41
I think a perfectly fine solution to (2) is for users that define STBTT_STATIC to also insert the appropriate pragmas for whatever compiler they're using to turn off unused function warnings. That option exists as a convenience feature for people who want to wrap stb_truetype themselves, and same as with the options to turn off individual image formats in stb_image, I'm now very much tending towards "if you want to do that and it causes warnings in your setup, it's on you to deal with the result".

**Closed by rygorous** 2021-07-07 09:41 UTC
Labels: 1 stb_truetype, 2 warning
