### ISSUE TITLE
Load image to a given memory buffer?

### ISSUE THREAD

**Issue by psionic12** [nothings/stb#996] opened 2020-07-15 14:53 UTC
Hi there, 
In my case I need to add some information before the loaded data, but I found that `stbi_load` allocate the memory by it self, which leads me have to copy the loaded data to another buffer, which is a waste of efficiency.

So is there any way I can give a memory to the stb?

**Comment by haozhan** [comment] 2020-07-17 05:20
Have stbi_load_from_memory, load the map from memory, don't know if can solve your problem.

**Comment by psionic12** [comment] 2020-07-17 05:50
I think I need some sort of load_to, not load from.

**Comment by Manuzor** [comment] 2020-07-17 06:07
@haozhan that's where the source image is loaded from. I believe the OP is trying to take control of where the destination image lands.

@psionic12 You can provide your own versions of `STBI_MALLOC`, `STBI_REALLLOC(_SIZED)`, and `STBI_FREE`. See here: https://github.com/nothings/stb/blob/b42009b3b9d4ca35bc703f5310eedc74f584be58/stb_image.h#L648-L652

So I guess you could sneak your own data in there like this:

```c
#define STBI_MALLOC(sz) my_stbi_alloc(sz)
#define STBI_REALLOC(p,newsz) my_stbi_realloc(p,newsz)
#define STBI_FREE(p) my_stbi_free(p)

struct my_header_data {
    int more_info;
    char padding_for_good_measure[4 + 8];
};

static void my_stbi_alloc(size_t sz) {
    struct my_header_data *header = malloc(sizeof(my_header_data) + sz);
    header->more_info = 42; // whatever
    return header + 1;
}

static void* my_stbi_realloc(void* p, size_t newsz) {
    return (struct my_header_data*)realloc((struct my_header_data*)p - 1, newsz) + 1;
}

static void my_stbi_free(void* p) {
    free((struct my_header_data*)p - 1);
}

#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

// ...

int main(int argc, char const* argv[]) {
    int x,y,n;
    unsigned char *data = stbi_load(filename, &x, &y, &n, 0);
    // ... process data if not NULL ...
    if(data) {
        struct my_header_data *header = (struct my_header_data*)data - 1;
        // header->more_info == 42;
    }
    // ... x = width, y = height, n = # 8-bit components per pixel ...
    // ... replace '0' with '1'..'4' to force that many components per pixel
    // ... but 'n' will always be the number that it would have been if you said 0
    stbi_image_free(data);
    return 0;
}
```

It would be nice to have some kind of `struct stbi_load_context { void* user; }` but I don't think that's going to happen. So if you want to pass a context into your allocators, it's going to have to happen via global variables.

**Comment by nothings** [comment] 2020-07-17 08:46
That isn't really appropriate because it also allocates other temporary memory buffers. I mean, I guess it would work, but it's pretty awkward.

Anyway, this is a duplicate of #58.

**Closed by nothings** 2020-07-17 08:46 UTC
