### ISSUE TITLE
stb_truetype SDF artifacts

### ISSUE THREAD

**Issue by ybungalobill** [nothings/stb#1115] opened 2021-03-22 16:17 UTC
There are some artifacts in the generated SDF. The following parameters

	scale = stbtt_ScaleForMappingEmToPixels(&font, 128);
	bitmap = stbtt_GetCodepointSDF(&font, scale, '!', 16, 128, 8, &w, &h, &xoff, &yoff);

with the Baloo2-Bold.ttf font ([available from Google Fonts](https://fonts.google.com/specimen/Baloo+2)) produces the following image:

![image](https://user-images.githubusercontent.com/11180281/112021744-fbc5ac80-8b07-11eb-9203-85bc8cde79a4.png)

Some other glyphs have similar artifacts.

**Comment by ybungalobill** [comment] 2021-03-23 04:57
Findings: the artifact was caused by a curve with the control point almost at the middle. stbtt was dividing by that almost-zero distance, thus messing up the calculation. In the proposed fix I compare the values up to epsilon = 1/128th of a pixel.

**Comment by rygorous** [comment] 2021-07-07 09:15
This appears to be fixed by commit fc5b791228c85cae0a4652254b78e35846504fe1 in the dev branch, which fixed issue #1069. Will be in the next release,

**Closed by rygorous** 2021-07-07 09:15 UTC
Labels: 1 stb_truetype, 2 bug

**Comment by nothings** [comment] 2021-07-07 09:28
Just to be clear, I don't think the listed commit made any difference to this, it was presumably fixed by some other PR.

**Comment by rygorous** [comment] 2021-07-08 07:14
Or maybe I missed the bug? I just used your command-line visualization, I
don't have anything better around.

**Comment by nothings** [comment] 2021-07-08 07:29
I just mean I tested before/after my commit (with the command-line output) and it looked the same to me (and looks fixed to me).

**Comment by lassade** [comment] 2024-11-25 15:30
Was this issue resolved? Because I'm getting a different kind of artifac like this:

Karla-Regular.ttf, lowercase 't'
![image](https://github.com/user-attachments/assets/38b8ffc6-deb5-46c3-af0d-82c2d6f81db0)

The issue is more pronounced when rendering bigger letters, but still there

**Comment by ybungalobill** [comment] 2024-11-26 20:27
For the record, I see this was merged [in July](https://github.com/nothings/stb/commit/6e9f34d5429cf16790ec43c9bac3f1ee4ad1f760) this year.

Thank you @nothings for the great libs and for the inspiration!
