### ISSUE TITLE
Kerning problem

### ISSUE THREAD

**Issue by Darky-Lucera** [nothings/stb#1250] opened 2021-11-19 10:22 UTC
**Describe the bug**

When I get the kerning table I can see kerning for some pairs of letters that are returning 0 when I call stbtt_GetCodepointKernAdvance().

**To Reproduce**

**Example 1:** Arial.ttf.
The first kerning pair is: 3 (' '), 36 ('A') -> -113

stbtt_GetCodepointKernAdvance(&info, ' ', 'A') returns 0.

This is due to arial has gpos and kerning.

**Example 2:** Cartoon_Regular.ttf -> https://fontsdata.com/4057/cartoon.htm
The first kerning pair is: 60 ('Y'), 15 (',') -> -260

stbtt_GetCodepointKernAdvance(&info, 'Y', ',') returns 0.

But this font does not have gpos, so it is calling stbtt__GetGlyphKernInfoAdvance(info, g1, g2);

**Expected behavior**

Get the same value.

**Comment by nothings** [comment] 2021-11-19 12:01
The font you linked to does not have either a "gpos" table _or_ a "kern" table, so neither GetKerningTable nor GetCodepointKernAdvance do anything.

I assume the problem you're trying to communicate is that GetKerningTable and GetCodepointKernAdvance give different results because the first only uses the 'kern' table and the second uses both 'kern' and 'gpos', and prioritizes gpos. (You should probably mention GetKerningTable explicitly if that's the case.) I noted this when I landed #808 which added GetKerningTable support without supporting gpos. I'm not going to fix it myself, it's going to need somebody to make a PR.

**Comment by Darky-Lucera** [comment] 2021-11-19 19:26
> The font you linked to does not have either a "gpos" table or a "kern" table, so neither GetKerningTable nor GetCodepointKernAdvance do anything.

I don't understand why are you telling this. Because:

 - According to FontDrop it has 230 kerning pairs. 

 - Calling std_truetype function stbtt_GetKerningTable it also returns 230 kerning pairs.

--

The problem is that calling stbtt_GetCodepointKernAdvance always returns 0 for any pair on this font.

**Comment by nothings** [comment] 2021-11-19 20:20
Did you download the font from the link you gave to verify this?

**Comment by Darky-Lucera** [comment] 2021-11-19 23:28
Yes, I did. This is weird. Did you upload it to FontDrop?

**Comment by Darky-Lucera** [comment] 2021-11-19 23:30
![image](https://user-images.githubusercontent.com/9335325/142703746-fa1b6dff-f30d-4c9e-b126-cefa32fb6163.png)

...

![image](https://user-images.githubusercontent.com/9335325/142703820-46ccd95c-259e-46b1-9b6b-3ab4dfe8bccc.png)

**Comment by Darky-Lucera** [comment] 2021-11-19 23:34
I have attached the file here:
[Cartoon_Regular.zip](https://github.com/nothings/stb/files/7573409/Cartoon_Regular.zip)

**Comment by nothings** [comment] 2021-11-20 01:01
The actual bug is that the 'kern' table in this font is broken.

(First, an aside, I apologize about the font confusion, in my text code I was explicitly specifying to load your font but my code was secretly loading a different font without me realizing, and since I was only looking at the tables and not rendering any text I didn't notice. Anyway, the font appears to only have kern, not both gpos and kern, so the issue is nothing to do with the other stuff I was talking about, sorry!)

Anyhow, because the kern table is broken, it is likely that other software that accesses it should have the same problem. The TrueType/OpenType specification requires the entries to be sorted so software can do a binary search to locate a kerning table entry. However, the table is not in sorted order.

You can see this in the output from FontDrop, or look at this list of the first six entries; the sixth is out of order.

![image](https://user-images.githubusercontent.com/7525026/142708528-ef66ff0e-aff9-4430-b878-29a8699cd645.png)

So, the two results are inconsistent because the kern definition is invalid, and this is the expected behavior.

**Closed by nothings** 2021-11-20 01:01 UTC
